################################################################################
# General Light-related automations (all lights)                               #
################################################################################
- alias: Turn Lights Off When Away During Day
  id: turn-lights-off-when-away-during-day
  trigger:
      platform: state
      entity_id: device_tracker.555924e18d8ed3d2
      from: 'home'
  condition:
    condition: and  # 'when light' condition: either after sunrise and before sunset
    conditions:
      - condition: sun
        after: sunrise
      - condition: sun
        before: sunset
  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_off
      entity_id: light.kitchenbulb2level_on_off
    - service: homeassistant.turn_off
      entity_id: switch.workbenchlight_switch
    - service: homeassistant.turn_off
      entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
    - service: homeassistant.turn_off
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0b0886_10
    - service: homeassistant.turn_off
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0afc46_10
    - service: homeassistant.turn_off
      entity_id: light.ge_45606_2way_dimmer_switch_level
    - service: homeassistant.turn_off
      entity_id: light.ge_45606_2way_dimmer_switch_level_2
    - service: homeassistant.turn_off
      entity_id: switch.inovelli_unknown_type_ff00_id_ff07_switch
- alias: Turn Lights Off During Day When Away
  id: turn-lights-off-during-day-when-away
  trigger:
      platform: sun
      event: sunrise
      offset: '+00:00:00'
  condition:
    condition: state
    entity_id: device_tracker.555924e18d8ed3d2
    state: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_off
      entity_id: light.kitchenbulb2level_on_off
    - service: homeassistant.turn_off
      entity_id: switch.workbenchlight_switch
    - service: homeassistant.turn_off
      entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
    - service: homeassistant.turn_off
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0b0886_10
    - service: homeassistant.turn_off
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0afc46_10
    - service: homeassistant.turn_off
      entity_id: light.ge_45606_2way_dimmer_switch_level
    - service: homeassistant.turn_off
      entity_id: light.ge_45606_2way_dimmer_switch_level_2
    - service: homeassistant.turn_off
      entity_id: switch.inovelli_unknown_type_ff00_id_ff07_switch
- alias: Turn Lights On 30m Before Sunset When Away and Randomlights Off
  id: turn-lights-on-30m-before-sunset-when-away-and-random-off
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.555924e18d8ed3d2
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.enable_randomlights
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb2level_on_off
    - service: homeassistant.turn_on
      entity_id: light.ge_45606_2way_dimmer_switch_level_2
- alias: Turn Lights On At Sunset If Away and Randomlights Off
  id: turn-lights-on-at-sunset-if-away-and-random-off
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.555924e18d8ed3d2
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.enable_randomlights
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb2level_on_off
    - service: homeassistant.turn_on
      entity_id: light.ge_45606_2way_dimmer_switch_level_2
- alias: Turn Lights On If Away After Sunset and Randomlights Off
  id: turn-lights-on-if-away-after-sunset-and-random-off
  trigger:
      platform: state
      entity_id: device_tracker.555924e18d8ed3d2
      from: 'home'
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
      - condition: state
        entity_id: input_boolean.enable_randomlights
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb2level_on_off
    - service: homeassistant.turn_on
      entity_id: light.ge_45606_2way_dimmer_switch_level_2
################################################################################
# Kitchen Lights                                                               #
################################################################################
- id: KitchenLightMotionOn
  alias: Turn Kitchen Light On When Motion Detected
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb2level_on_off
- alias: Turn Kitchen Light Off 10 Minutes After Motion
  id: KitchenLightMotionOff
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_off
      entity_id: light.kitchenbulb2level_on_off
################################################################################
# Porch Lights                                                                 #
################################################################################
- id: PorchLightFrontDoorOn
  alias: Turn Porch Light On When Front Door Opened After Sunset
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor
    to: 'on'
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    - service: homeassistant.turn_on
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0afc46_10
    - service: homeassistant.turn_on
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0b0886_10
- alias: Turn Porch Light Off 10 Minutes After Door Open After Sunset
  id: PorchLightFrontDoorOff
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor
    to: 'off'
    for:
      minutes: 10
  # turn off the light after motion, after sunset, only when I'm home
  condition:
    - condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    - condition: state
      entity_id: device_tracker.555924e18d8ed3d2
      state: 'home'
  action:
    - service: homeassistant.turn_off
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0afc46_10
    - service: homeassistant.turn_off
      entity_id: light.cree_connected_a_19_60w_equivalent_fe0b0886_10
- id: PorchLightOnDimWhenAwayAtSunset
  alias: Turn Porch Light On Dim When Away At Sunset
  trigger:
      platform: sun
      event: sunset
      offset: '+00:00:00'
  condition:
    condition: state
    entity_id: device_tracker.555924e18d8ed3d2
    state: 'not_home'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.cree_connected_a_19_60w_equivalent_fe0b0886_10
      white_value: 127
- id: PorchLightOnDimWhenSunsetAndAway
  alias: Turn Porch Light On Dim When Sunset and Away
  trigger:
      platform: state
      entity_id: device_tracker.555924e18d8ed3d2
      to: 'not_home'
  condition:
    # it must be dark out
    - condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.cree_connected_a_19_60w_equivalent_fe0b0886_10
      white_value: 127
- id: PorchLightsOffAtSunrise
  alias: Turn Porch Lights Off At Sunrise
  trigger:
      platform: sun
      event: sunrise
      offset: '+00:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.cree_connected_a_19_60w_equivalent_fe0b0886_10
    - service: light.turn_off
      data:
        entity_id:
          - light.cree_connected_a_19_60w_equivalent_fe0afc46_10
- id: PorchLightOnFullWhenArrivingHomeAfterSunset
  alias: Porch Light On Full When Arriving Home After Sunset
  trigger:
      platform: numeric_state
      entity_id: proximity.home
      below: 1000 # meters
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.cree_connected_a_19_60w_equivalent_fe0afc46_10
        white_value: 255
    - service: light.turn_on
      data:
        entity_id:
          - light.cree_connected_a_19_60w_equivalent_fe0b0886_10
        white_value: 255
################################################################################
# Living Room Light                                                            #
################################################################################
- id: LivingRoomLightOnWhenDoorOpenedAtNight
  alias: Turn Living Room Light On When Front Door Opened At Night
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor
    to: 'on'
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    - service: homeassistant.turn_on
      entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
################################################################################
# BEGIN "first morning" routine                                                #
# from https://www.home-assistant.io/cookbook/automation_first_light/          #
################################################################################
- alias: Enable First Morning Trigger
  id: enable-first-morning-trigger
  trigger:
    - platform: time
      at: '4:00'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.trigger_first_morning
# "first morning" routine - turns it off 5 hours after sunrise
- alias: Disable First Morning Trigger
  id: disable-first-morning-trigger
  trigger:
    - platform: sun
      event: sunrise
      offset: "05:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.trigger_first_morning
# "first morning" motion trigger
- alias: First Morning Button Trigger
  id: first-morning-button-trigger
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:9a:2b:be
      unique_id: 00:15:8d:00:07:9a:2b:be:1:0x0012
      command: single
  # only complete the automation if we're still waiting for the first motion
  condition:
    - condition: state
      entity_id: input_boolean.trigger_first_morning
      state: 'on'
    - condition: state
      entity_id: device_tracker.555924e18d8ed3d2
      state: 'home'
  action:
    # turn off the "waiting" boolean regardless of whether lights will turn on
    # so that this happens only once
    - service: homeassistant.turn_off
      entity_id: input_boolean.trigger_first_morning
    - service: homeassistant.turn_on
      entity_id: light.ge_45606_2way_dimmer_switch_level
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb1level_on_off
    - service: homeassistant.turn_on
      entity_id: light.kitchenbulb2level_on_off
    - service: homeassistant.turn_on
      entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
    - service: homeassistant.turn_on
      entity_id: light.ge_45606_2way_dimmer_switch_level_2
################################################################################
# END "first morning" routine                                                  #
################################################################################
################################################################################
# Aqara Zigbee Buttons                                                         #
################################################################################
- alias: Bedroom Lights On
  id: bedroom-lights-on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:9a:2b:be
      unique_id: 00:15:8d:00:07:9a:2b:be:1:0x0012
      command: single
  action:
    - service: homeassistant.turn_on
      entity_id: group.commonlights
- alias: Bedroom Lights Off
  id: bedroom-lights-off
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:9a:2b:be
      unique_id: 00:15:8d:00:07:9a:2b:be:1:0x0012
      command: double
  action:
    - service: homeassistant.turn_off
      entity_id: group.indoorlights
- alias: BackRoom Lights On
  id: backroom-lights-on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:5e:1f:4c
      unique_id: 00:15:8d:00:07:5e:1f:4c:1:0x0012
      command: single
  action:
    - service: homeassistant.turn_on
      entity_id: group.backroomlights
- alias: BackRoom Lights Off
  id: backroom-lights-off
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:5e:1f:4c
      unique_id: 00:15:8d:00:07:5e:1f:4c:1:0x0012
      command: double
  action:
    - service: homeassistant.turn_off
      entity_id: group.backroomlights
################################################################################
# END Aqara Zigbee Buttons                                                     #
################################################################################
################################################################################
# BEGIN sengled zigbee remote 1                                                #
################################################################################
- alias: Sengled BackRoom Lights On
  id: sengled-backroom-lights-on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: b0:ce:18:14:03:6a:0e:16
      unique_id: b0:ce:18:14:03:6a:0e:16:1:0x0006
      command: on
  action:
    - service: homeassistant.turn_on
      entity_id: group.backroomlights
- alias: Sengled BackRoom Lights Off
  id: sengled-backroom-lights-off
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: b0:ce:18:14:03:6a:0e:16
      unique_id: b0:ce:18:14:03:6a:0e:16:1:0x0006
      command: off
  action:
    - service: homeassistant.turn_off
      entity_id: group.backroomlights
################################################################################
# END sengled zigbee remote 1                                                  #
################################################################################
################################################################################
# Alarm Automations                                                            #
################################################################################
- alias: Arm after motion in bedroom, at night, when home, and house is dark.
  id: arm-after-motion-in-bedrom-at-night-when-home-house-dark
  trigger:
    # Trigger 2 minutes after bedroom_motion set to off
    platform: state
    entity_id: binary_sensor.bedroom_motion
    to: 'off'
    for:
      minutes: 2
  condition:
    # device must be home
    - condition: state
      entity_id: device_tracker.555924e18d8ed3d2
      state: 'home'
    # it must be dark out
    - condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    # it must be after 7pm or before 5am
    - condition: or
      conditions:
        - condition: time
          after: '19:00:00'
        - condition: time
          before: '05:00:00'
    # bedroom light must be off
    - condition: state
      entity_id: light.ge_45606_2way_dimmer_switch_level
      state: 'off'
    # office light must be off
    - condition: state
      entity_id: light.ge_45606_2way_dimmer_switch_level_2
      state: 'off'
    # living room luminance must be less than 5 PERCENT (Zooz multi-sensor)
    - condition: numeric_state
      entity_id: sensor.lrmotion_luminance
      below: 5
  action:
    - event: CUSTOM_ALARM_STATE_SET
      event_data:
        state: Home
- alias: Arm after living room light is shut off, at night, when home
  id: arm-after-living-room-light-is-shut-off-at-night-when-home
  trigger:
    platform: state
    entity_id: light.jasco_products_45606_2_way_dimmer_switch_level
    to: 'off'
  condition:
    # device must be home
    - condition: state
      entity_id: device_tracker.555924e18d8ed3d2
      state: 'home'
    # it must be dark out
    - condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
    # it must be after 7pm or before 5am
    - condition: or
      conditions:
        - condition: time
          after: '19:00:00'
        - condition: time
          before: '05:00:00'
  action:
    - event: CUSTOM_ALARM_STATE_SET
      event_data:
        state: Home
- alias: Arm at 2100 if I am home
  id: arm-at-2100-if-I-am-home
  trigger:
    platform: time
    at: "21:00:00"
  condition:
    # device must be home
    - condition: state
      entity_id: device_tracker.555924e18d8ed3d2
      state: 'home'
  action:
    - event: CUSTOM_ALARM_STATE_SET
      event_data:
        state: Home
- alias: Arm at 2300 if I am home
  id: arm-at-2300-if-I-am-home
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    # device must be home
    - condition: state
      entity_id: device_tracker.555924e18d8ed3d2
      state: 'home'
  action:
    - event: CUSTOM_ALARM_STATE_SET
      event_data:
        state: Home
