- platform: template
  sensors:
    office_motion:
      value_template: "{{ states('sensor.officesensor_burglar')|float > 0 }}"
      friendly_name: "Office Motion"
      device_class: motion
    livingroom_motion:
      value_template: "{{ states('sensor.lrmotion_burglar')|float > 0 }}"
      friendly_name: "Living Room Motion"
      device_class: motion
    kitchen_motion:
      value_template: "{{ states('sensor.kitchensensor_burglar')|float > 0 }}"
      friendly_name: "Kitchen Motion"
      device_class: motion
    bedroom_motion:
      value_template: "{{ states('sensor.bedroomsensor_burglar')|float > 0 }}"
      friendly_name: "Bedroom Motion"
      device_class: motion
