title: Bed
views:
  - title: Home
    path: home
    badges: []
    cards:
      - !include /config/lovelace/floorplan.yaml
      - type: entity
        entity: sensor.time
      - type: grid
        cards:
          - type: button
            entity: light.ge_45606_2way_dimmer_switch_level
            tap_action:
              action: more-info
          - type: button
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.bedpi_display
            entity: switch.bedpi_display
            icon: 'mdi:tablet-dashboard'
            name: Display Off
          - type: button
            tap_action:
              action: toggle
              service_data:
                entity_id: switch.bedroomtvpower_on_off
            entity: switch.bedroomtvpower_on_off
            icon: 'mdi:television'
            name: Bedroom TV
      - type: entities
        title: Alarm
        entities:
          - input_select.alarmstate
          - input_boolean.bedpi_display_wake
          - input_boolean.alarm_duress
  - title: Front
    path: front
    cards:
      - type: picture-entity
        entity: camera.front
  - title: Porch
    path: porch
    cards:
      - type: picture-entity
        entity: camera.porch
  - title: Cameras
    path: cameras
    badges: []
    cards:
      - !include /config/lovelace/cameras.yaml
  - title: Lights
    path: lights
    badges: []
    cards:
      - !include /config/lovelace/lights.yaml
  - title: Climate
    path: climate
    badges: []
    cards:
      - type: thermostat
        entity: climate.officelightswitch_mode
      - type: weather-forecast
        entity: weather.dark_sky
  - title: Alarm
    path: alarm
    badges: []
    cards:
      - type: entities
        entities:
          - entity: input_select.alarmstate
          - entity: input_boolean.alarm_duress
          - entity: input_boolean.enable_motion
          - entity: input_boolean.cameras_silent
  - title: Ignore
    path: ignore
    badges: []
    cards:
      - !include /config/lovelace/alarm-ignore.yaml
