title: Bed
views:
  - title: Home
    path: home
    badges: []
    cards:
      - !include /config/lovelace/floorplan.yaml
      - type: entity
        entity: sensor.time
      - type: entity
        entity: sensor.porch_temp
  - title: Cameras
    path: cameras
    badges: []
    cards:
      - !include /config/lovelace/cameras.yaml
  - title: Lights
    path: lights
    badges: []
    cards:
      - type: light
        entity: light.jasco_products_45606_2_way_dimmer_switch_level
      - type: entities
        entities:
          - entity: light.ge_45606_2way_dimmer_switch_level_2
          - entity: light.linear_lb60z1_dimmable_led_light_bulb_level
          - entity: >-
              light.linear_nortek_security_control_llc_lb60z_1_dimmable_led_light_bulb_level
          - entity: light.cree_connected_a_19_60w_equivalent_fe0b0886_10
          - entity: light.cree_connected_a_19_60w_equivalent_fe0afc46_10
  - title: Climate
    path: climate
    badges: []
    cards:
      - type: thermostat
        entity: climate.officelightswitch_mode
      - type: weather-forecast
        entity: weather.dark_sky
  - title: Alarm
    path: alarm
    badges: []
    cards:
      - type: entities
        entities:
          - entity: input_select.alarmstate
          - entity: input_boolean.alarm_duress
          - entity: input_boolean.enable_motion
          - entity: input_boolean.cameras_silent
