# see: https://github.com/ciotlosm/docs-lovelace
name: Non-Shitty UI
views:
  - name: Main
    title: Main
    id: main
    theme: this-doesnt-work
    cards:
      # LEFT COLUMN
      - type: vertical-stack
        cards:
        - !include /config/lovelace/floorplan.yaml
        - type: picture-entity
          entity: switch.side_state
          camera_image: camera.side
          state_filter:
        - type: picture-entity
          entity: switch.hall_state
          camera_image: camera.hall
        - type: thermostat
          name: Climate
          entity: climate.z_wave_thermostat
      # CENTER COLUMN
      - type: vertical-stack
        cards:
        - type: entities
          show_header_toggle: false
          title: Controls
          entities:
            - input_select.alarmstate
            - input_boolean.cameras_silent
            - switch.linear_wa105dbz1_main_operated_siren_switch
            - input_boolean.no_alarm_delay
            - group.lights
            - input_boolean.enable_randomlights
            - input_boolean.enable_motion
            - input_boolean.alarm_duress
        - type: picture-entity
          entity: switch.porch_state
          camera_image: camera.porch
        - type: picture-entity
          entity: switch.front_state
          camera_image: camera.front
        - type: picture-entity
          entity: switch.bedrm_state
          camera_image: camera.bedrm
        - !include /config/lovelace/lights.yaml
        - !include /config/lovelace/alarm-ignore.yaml
      # RIGHT COLUMN
      - type: vertical-stack
        cards:
        - type: picture-entity
          entity: switch.back_state
          camera_image: camera.back
        - type: picture-entity
          entity: switch.gate_state
          camera_image: camera.gate
        - type: picture-entity
          entity: switch.lrkitchen_state
          camera_image: camera.lrkitchen
        - type: picture-entity
          entity: switch.office_state
          camera_image: camera.office
        - type: picture-entity
          entity: switch.garage_state
          camera_image: camera.garage
        - type: weather-forecast
          entity: weather.dark_sky
        - type: picture-entity
          entity: switch.north_state
          camera_image: camera.north
        - type: picture-entity
          entity: switch.south_state
          camera_image: camera.south
        - type: entities
          show_header_toggle: false
          title: Cameras
          entities:
            - sensor.back_events
            - sensor.back_status
            - switch.back_state
            - sensor.bedrm_events
            - sensor.bedrm_status
            - switch.bedrm_state
            - sensor.lrkitchen_events
            - sensor.lrkitchen_status
            - switch.lrkitchen_state
            - sensor.office_events
            - sensor.office_status
            - switch.office_state
            - sensor.porch_events
            - sensor.porch_status
            - switch.porch_state
            - sensor.front_events
            - sensor.front_status
            - switch.front_state
            - sensor.garage_events
            - sensor.garage_status
            - switch.garage_state
            - sensor.side_events
            - sensor.side_status
            - switch.side_state
            - sensor.hall_events
            - sensor.hall_status
            - switch.hall_state
            - sensor.north_events
            - sensor.north_status
            - switch.north_state
            - sensor.south_events
            - sensor.south_status
            - switch.south_state
            - sensor.gate_events
            - sensor.gate_status
            - switch.gate_state
      # END RIGHT COLUMN - NO MORE COLUMNS!
